-- Language support — OVERRIDES live here.
--
-- The extra IMPORTS are in config/lazy.lua, NOT here. LazyVim requires extras
-- to be imported after `lazyvim.plugins` and before your own `plugins/` files,
-- and everything in this folder loads last — so the imports can't live here
-- without tripping LazyVim's import-order check.
--
-- This is the place for your own language tweaks. Example — extra vtsls
-- settings (uncomment and edit):
return {
  -- {
  --   "neovim/nvim-lspconfig",
  --   opts = {
  --     servers = {
  --       vtsls = {
  --         settings = {
  --           typescript = {
  --             preferences = { importModuleSpecifier = "non-relative" },
  --           },
  --         },
  --       },
  --     },
  --   },
  -- },
}
